In [1]:
# Numpy:

In [2]:
# ndim
# shape

In [3]:
import numpy as np

In [4]:
# reshape:------

In [5]:
# 1d -- 2d, 3d, ...nd

In [6]:
x = np.array([12, 34, 23, 45, 567, 45, 23, 12, 34, 100, 89])

In [8]:
x.ndim

1

In [9]:
x.shape

(11,)

In [10]:
x = [23, 45, 23, 56, 78, 354, 23, 56, 100]

In [11]:
len(x)

9

In [24]:
x = np.array([12, 34, 23, 45, 567, 45, 23, 12, 34, 100, 89, 34])

In [25]:
len(x)

# 6, 6

12

In [37]:
x.reshape(2, 3, 2)

array([[[ 12,  34],
        [ 23,  45],
        [567,  45]],

       [[ 23,  12],
        [ 34, 100],
        [ 89,  34]]])

In [27]:
# -1

In [28]:
x = np.array([12, 34, 23, 45, 567, 45, 23, 12, 34, 100, 89, 34])

In [30]:
x.reshape(2, -1)

array([[ 12,  34,  23,  45, 567,  45],
       [ 23,  12,  34, 100,  89,  34]])

In [33]:
x.reshape(-1, 4)

array([[ 12,  34,  23,  45],
       [567,  45,  23,  12],
       [ 34, 100,  89,  34]])

In [40]:
zx = np.array([[34,23, 45, 32, 45, 23], [45, 67, 4,5, 6, 56]])

In [41]:
zx.ndim

2

In [42]:
zx.reshape(-1)

array([34, 23, 45, 32, 45, 23, 45, 67,  4,  5,  6, 56])

In [43]:
# important functions:::::::::

In [44]:
# 1) unique()

In [45]:
# random

In [46]:
# import random

In [48]:
from numpy import random

In [79]:
zx = random.randint(1, 50)

In [80]:
zx

27

In [87]:
zx = random.randint(1, 50, size = (5, 3))

In [88]:
zx

array([[31, 40, 25],
       [42, 22, 38],
       [14, 25, 36],
       [46, 28, 24],
       [15, 46, 49]])

In [89]:
# random.rand()

In [ ]:
# 0 ------ 1

In [91]:
random.rand(2, 3)

array([[0.46782225, 0.40678913, 0.86617661],
       [0.39492125, 0.31591451, 0.6293492 ]])

In [92]:
# choice()

In [99]:
xp = random.choice([23, 45, 56, 23, 45, 23, 45, 23, 100], size = (3, 3))
xp

array([[100,  23,  56],
       [ 56,  23, 100],
       [ 45,  23,  23]])

In [ ]:
zx = 002340030403403

In [ ]:
output:

totel number zeros : 5
the sum of 2, 3, 4, 3, 4, 4, 3 is : 20