In [2]:
# Numpy:

### start numpy

In [ ]:
numpy ====> numarical python

    2005
    Travis Oliphant
    

In [ ]:
# list
# tuple set dictionry

In [3]:
# list --> hitrogenious

In [ ]:
numpy
    70%    python
    30%    c/c++


50x faster then list

In [ ]:
# arrays : 

In [4]:
!pip install numpy

DEPRECATION: textract 1.6.5 has a non-standard dependency specifier extract-msg<=0.29.*. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of textract or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [ ]:
jupyter notebook .

## numpy ndarrys

In [ ]:
1) ndarray -> n dimational arrays!

    when we create any obect with the help of array method in numpy. that object us called ndarray..

In [5]:
import numpy as np

In [6]:
arr = np.array(10)

In [7]:
x = 10

In [8]:
type(x)

int

In [9]:
type(arr)

numpy.ndarray

In [10]:
arr

array(10)

In [12]:
# attribute:::::


        # ndim ---> return dimmession of an ndarrayyyy

In [13]:
arr.ndim

0

## crate 1-d ndarray/..

In [14]:
x = np.array([12, 45, 23, 100, 90])

In [15]:
x

array([ 12,  45,  23, 100,  90])

In [17]:
x.ndim

1

In [18]:
# 2d nd array

In [22]:
y = np.array([[23, 45, 23, 10], [45, 67, 34, 20]])

In [23]:
y

array([[23, 45, 23, 10],
       [45, 67, 34, 20]])

In [24]:
y.ndim

2

In [31]:
z = np.array([[[12, 34, 20], [45, 34, 23]] , [[34, 56, 34], [54, 34, 23]]])

In [32]:
z

array([[[12, 34, 20],
        [45, 34, 23]],

       [[34, 56, 34],
        [54, 34, 23]]])

In [33]:
z.ndim

3

In [ ]:
[[[23, 45, 23, 10], [45, 34, 23, 10], [45, 34, 123, 34]], [[45, 45, 23, 34], [45, 3, 23, 2], [45, 23, 23, 34]]]

In [34]:
xyz = np.array([[[[[[23]]]]]])

In [35]:
xyz.ndim

6

In [36]:
# indexing in ndarry

In [37]:
# 1-d 

In [38]:
x = np.array([12, 34, 56, 20, 100, 56, 19])

In [40]:
p = x[4]

In [41]:
p

100

In [42]:
x[2]

56

In [43]:
x[-3]

100

In [44]:
# indexing with 2d ndarray

In [46]:
zx = np.array([[12, 34, 23, 5, 10], [56, 45, 23, 100, 78]])

In [47]:
zx

array([[ 12,  34,  23,   5,  10],
       [ 56,  45,  23, 100,  78]])

In [48]:
zx.ndim

2

In [50]:
zx[1][2]

23

In [52]:
zx[0][3]

5

In [53]:
zx[1][2], zx[0][3]

(23, 5)

In [54]:
pqr = np.array([[[12, 34, 10], [34, 23, 10], [23, 345, 10]], [[34, 23, 45], [56, 23, 12], [34, 23, 2]]])

In [55]:
pqr.ndim

3

In [58]:
pqr[1][1][0]

56

In [59]:
pqr[0][2][1]

345

In [60]:
pqr[1][2][2]

2

In [61]:
# slicing::::::::::::::::::: with ndarray

In [ ]:
objname[start : end : increment]

In [ ]:
    # start ::: 0
    # end ::: n - 1
    # increment :: 1

In [62]:
# slicing with 1d ndarray

In [64]:
qw = np.array([34, 23, 45, 23, 10, 9900, 78, 34, 12, 34])

In [66]:
qw[2 : 8]

array([  45,   23,   10, 9900,   78,   34])

In [67]:
qw[5 : ]

array([9900,   78,   34,   12,   34])

In [69]:
qw[4 : 8 : 3]

array([10, 34])

In [70]:
qw

array([  34,   23,   45,   23,   10, 9900,   78,   34,   12,   34])

In [71]:
qw[: : -1]

array([  34,   12,   34,   78, 9900,   10,   23,   45,   23,   34])

In [72]:
# slicing with 2-d ndarray

In [73]:
xyz = np.array([[12, 23, 45, 23, 67, 4, 100], [78, 45, 23, 12, 10, 78, 23]])

In [74]:
xyz

array([[ 12,  23,  45,  23,  67,   4, 100],
       [ 78,  45,  23,  12,  10,  78,  23]])

In [76]:
xyz[1][1 : 6]

array([45, 23, 12, 10, 78])

In [ ]:
ndarray
ndim --- attribues
slicig
indexing
1-d array
2-d array
3-d ndarray

In [77]:
# ndarray ---> mutablee...

In [79]:
xyz = np.array([12, 100, 67, 78, 29, 100, 90, 688, 90, 128])

In [ ]:
# replacing elements ::::::::::: 

In [80]:
xyz

array([ 12, 100,  67,  78,  29, 100,  90, 688,  90, 128])

In [81]:
# objname[indexnumber] = newitem

In [82]:
xyz[-4] = 17

In [83]:
xyz

array([ 12, 100,  67,  78,  29, 100,  17, 688,  90, 128])

In [84]:
xyz[3] = 700

In [85]:
xyz

array([ 12, 100,  67, 700,  29, 100,  17, 688,  90, 128])

In [86]:
pqr = np.array([[[12, 34, 10], [34, 23, 10], [23, 345, 10]], [[34, 23, 45], [56, 23, 12], [34, 23, 2]]])

In [87]:
pqr[1][1][1]

23

In [90]:
pqr[1][2][2]

2

In [92]:
pqr[0][2][1]

345

## elemets add krne hai

In [93]:
# append()

In [94]:
xyz = np.array([34, 23, 56, 34, 100, 78])

In [95]:
# np.append(objname, elementname)

In [98]:
x = np.append(xyz, 3000)

In [97]:
xyz

array([ 34,  23,  56,  34, 100,  78])

In [99]:
x

array([  34,   23,   56,   34,  100,   78, 3000])

In [100]:
# insert()

In [101]:
# np.insert(objname, indexnumber,  item)

In [102]:
x

array([  34,   23,   56,   34,  100,   78, 3000])

In [103]:
np.insert(x, 1, 90)

array([  34,   90,   23,   56,   34,  100,   78, 3000])

In [104]:
x

array([  34,   23,   56,   34,  100,   78, 3000])

In [105]:
indexin = [1, 4, 5]
elemts = [1000, 2000, 300]

In [106]:
np.insert(x, indexin, elemts)

array([  34, 1000,   23,   56,   34, 2000,  100,  300,   78, 3000])