In [1]:
# Numpy : 

In [ ]:
indexing or slicing --> list

In [2]:
# ndarray :->

import numpy as np

In [3]:
arr = np.array([12, 34, 45, 23, 45])

In [4]:
# ndim -> to check dimmsion os ndarray
arr.ndim

1

In [5]:
arr.shape

(5,)

In [6]:
# indexing in 1-D Ndarray

In [7]:
arr = np.array([12, 34, 45, 23, 45])

In [8]:
# objectname[indexnumber]

arr[1]

34

In [9]:
arr[3]

23

In [10]:
arr[-2]

23

In [ ]:
# Slicing : 


# objectname[start : end : increment]

# default:
#     start : 0
#     end : n - 1
#     increrment : 1

In [11]:
arr = np.array([12, 34, 45, 23, 45])

In [12]:
arr[2 : 4 : 1]

array([45, 23])

In [13]:
arr[0 : 4 : 1]

array([12, 34, 45, 23])

In [14]:
arr[ : 4]

array([12, 34, 45, 23])

In [15]:
arr = np.array([12, 34, 45, 23, 45])

In [16]:
arr[1 : ]

array([34, 45, 23, 45])

In [18]:
arr[: : 3]

array([12, 23])

In [19]:
arr = np.array([12, 34, 45, 23, 45])

In [20]:
arr[ : : -1]

array([45, 23, 45, 34, 12])

In [21]:
# 2-D ndarrayyy lsicing indexing/


In [26]:
xyz = np.array([[12, 23, 45, 56, 67, 23], [23, 5, 6, 7, 8, 9]])

In [27]:
xyz

array([[12, 23, 45, 56, 67, 23],
       [23,  5,  6,  7,  8,  9]])

In [28]:
xyz.ndim

2

In [29]:
xyz.shape

(2, 6)

In [30]:
xyz = np.array([[12, 23, 45, 56, 67, 23], [23, 5, 6, 7, 8, 9]])

In [31]:
# indedxing   

# objectname[array_index][element_index]

In [36]:
xyz[1][1]

array([23,  5,  6,  7,  8,  9])

In [35]:
xyz[0][-1]

23

In [37]:
# slicing

In [38]:
xyz = np.array([[12, 23, 45, 56, 67, 23], [23, 5, 6, 7, 8, 9]])

In [39]:
xyz[1][1 : 4]

array([5, 6, 7])

In [40]:
# 3-D

In [49]:
zx = np.array([[[12, 34, 45, 23], [45, 67, 45, 3]],
                 [[12, 23, 43, 56], [67, 34, 23, 1]]])

In [50]:
zx

array([[[12, 34, 45, 23],
        [45, 67, 45,  3]],

       [[12, 23, 43, 56],
        [67, 34, 23,  1]]])

In [51]:
zx.ndim

3

In [52]:
zx.shape

(2, 2, 4)

In [53]:
zx = np.array([[[12, 34, 45, 23], [45, 67, 45, 3]], [[12, 23, 43, 56], [67, 34, 23, 1]]])

In [54]:
zx[0][1][3]

3

## numpy functions :

In [ ]:
numpy ---->  arange() 
python ----> range()

In [55]:
# np.arange(start, end, increment)

In [56]:
x = np.arange(5, 22, 1)
x

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [57]:
# 10, 9, 8, 7, 6, 5, 4, 3, 2

In [58]:
y = np.arange(10, 1, -1)
y

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [60]:
np.arange(2, 21, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [61]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.arange(1, 4)

array([1, 2, 3])

In [64]:
np.arange(10, 4, -1)


array([10,  9,  8,  7,  6,  5])

In [65]:
# sort() ---> sorting the data

In [66]:
zx = np.array([3, 4, 5, 3, 5, 7, 8, 45, 3, 2, 1])

In [67]:
# np.sort(objename)

In [68]:
np.sort(zx)

array([ 1,  2,  3,  3,  3,  4,  5,  5,  7,  8, 45])

In [71]:
np.sort(zx)[: : -1]

array([45,  8,  7,  5,  5,  4,  3,  3,  3,  2,  1])

In [72]:
zx

array([ 3,  4,  5,  3,  5,  7,  8, 45,  3,  2,  1])

In [ ]:
# where()

In [ ]:
where() ---> to get the indexnumber of elements based on condation.

In [73]:
pq = np.array([2, 3, 2, 3, 34, 23, 34, 1, 2, 45, 6, 7, 34, 23, 9])

In [ ]:
np.where(condation)

compersion operators:
    1) ==
    2) !=
    3) <
    4) >
    5) <=
    6) >=

In [74]:
pq = np.array([2, 3, 2, 3, 34, 23, 34, 1, 2, 45, 6, 7, 34, 23, 9])

In [75]:
np.where(pq == 9)

(array([14], dtype=int64),)

In [76]:
np.where(pq == 2)

(array([0, 2, 8], dtype=int64),)

In [77]:
np.where(pq > 20)

(array([ 4,  5,  6,  9, 12, 13], dtype=int64),)

In [ ]:
reshape() --> it help to chnage the shape of data..

1-D , ---> 2d, 3d
2-D ---> 3d, 1d, 10d

In [78]:

# 1D ---> 2D

In [83]:
zx = np.arange(2, 44, 3)

In [84]:
zx

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41])

In [85]:
len(zx)

14

In [ ]:
# np.reshape(objectname, newshape)

# objectbame.reshape(newshape)

In [87]:
zx.ndim

1

In [90]:
np.reshape(zx, (2, 7))

array([[ 2,  5,  8, 11, 14, 17, 20],
       [23, 26, 29, 32, 35, 38, 41]])

In [91]:
np.reshape(zx, (7, 2))

array([[ 2,  5],
       [ 8, 11],
       [14, 17],
       [20, 23],
       [26, 29],
       [32, 35],
       [38, 41]])

In [92]:
np.reshape(zx, (14, 1))

array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17],
       [20],
       [23],
       [26],
       [29],
       [32],
       [35],
       [38],
       [41]])

In [93]:
np.reshape(zx, (1, 14))

array([[ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41]])

In [96]:
zx = np.array([1, 4, 2, 3, 4, 5, 6, 4, 5, 4, 6, 4])

In [97]:
len(zx)

12

In [98]:
pq = np.reshape(zx, (4, 3))
pq

array([[1, 4, 2],
       [3, 4, 5],
       [6, 4, 5],
       [4, 6, 4]])

In [99]:
# -1 ---> automatically recognizee

In [100]:
zx = np.array([1, 4, 2, 3, 4, 5, 6, 4, 5, 4, 6, 4])

In [101]:
np.reshape(zx, (4, -1))

array([[1, 4, 2],
       [3, 4, 5],
       [6, 4, 5],
       [4, 6, 4]])

In [102]:
 np.reshape(zx, (2, -1))

array([[1, 4, 2, 3, 4, 5],
       [6, 4, 5, 4, 6, 4]])

In [103]:
np.reshape(zx, (6, -1))

array([[1, 4],
       [2, 3],
       [4, 5],
       [6, 4],
       [5, 4],
       [6, 4]])

In [105]:
np.reshape(zx, (3, -1))

array([[1, 4, 2, 3],
       [4, 5, 6, 4],
       [5, 4, 6, 4]])

In [106]:
np.reshape(zx, (-1, 4))

array([[1, 4, 2, 3],
       [4, 5, 6, 4],
       [5, 4, 6, 4]])

In [107]:
# 2D ---> 1D

In [108]:
zx = np.array([[23, 34, 45, 65, 3], [34, 23, 34, 2, 2]])

In [109]:
zx

array([[23, 34, 45, 65,  3],
       [34, 23, 34,  2,  2]])

In [110]:
np.reshape(zx, -1)

array([23, 34, 45, 65,  3, 34, 23, 34,  2,  2])

In [111]:
# List ---> mutable

# numpy array ---> mutable

In [113]:
zx = np.array([1, 2, 3, 8, 5, 7, 9, 10])

In [114]:
# REPLACE ELEMENTS : 

In [115]:
# syntex
    # objectname[indexnumber] = new_element

zx[2] = 500

In [116]:
zx

array([  1,   2, 500,   8,   5,   7,   9,  10])

In [117]:
zx = np.array([1, 2, 3, 8, 5, 7, 9, 10])

In [118]:
zx

array([ 1,  2,  3,  8,  5,  7,  9, 10])

In [119]:
inx = [2, 5, 7]
new_ele = [500, 1000, 600]

In [120]:
zx[inx] = new_ele

In [121]:
zx

array([   1,    2,  500,    8,    5, 1000,    9,  600])

In [122]:
zx[[2, 5, 7]] = [500, 1000, 600]

In [123]:
zx

array([   1,    2,  500,    8,    5, 1000,    9,  600])

In [124]:
# adding elements in ndarray:

In [125]:
zx = np.array([1, 2, 3, 8, 5, 7, 9, 10])

In [126]:
# append() --> to add new element at the end of ndarray..

# syntex:

# np.append(objectname, new_element)

In [128]:
np.append(zx, 200)

array([  1,   2,   3,   8,   5,   7,   9,  10, 200])

In [129]:
np.append(zx, [12, 34, 45, 567, 78])

array([  1,   2,   3,   8,   5,   7,   9,  10,  12,  34,  45, 567,  78])

In [130]:
zx

array([ 1,  2,  3,  8,  5,  7,  9, 10])

In [ ]:
1) empty ndaary    zx = np.array([])
2) add 2 table



array(['2 x 1 = 2', '2 x 2 = 4', '2 x 3 = 6',      . . ..  ,'2 x 10 = 20'])

In [131]:
zx = np.array([])

In [135]:
for i in np.arange(1, 11):
    zx = np.append(zx, f"2 x {i} = {2*i}")

In [136]:
zx

array(['2 x 1 = 2', '2 x 2 = 4', '2 x 3 = 6', '2 x 4 = 8', '2 x 5 = 10',
       '2 x 6 = 12', '2 x 7 = 14', '2 x 8 = 16', '2 x 9 = 18',
       '2 x 10 = 20'], dtype='<U32')

In [137]:
# insert() ---> help to add new element, at a perticter location..

In [138]:
# np.insert(objectname, indexnumber, newlement)

In [139]:
zx = np.array([1, 2, 3, 8, 5, 7, 9, 10])

In [140]:
np.insert(zx, 2, 400)

array([  1,   2, 400,   3,   8,   5,   7,   9,  10])

In [141]:
zx = np.array([1, 2, 3, 8, 5, 7, 9, 10])

np.insert(zx, [1, 5], [100, 500])

array([  1, 100,   2,   3,   8,   5, 500,   7,   9,  10])

In [142]:
# delete() ----> to deleted data

In [143]:
# np.delete(objectname, indexnumber)

In [144]:
zx = np.array([1, 2, 3, 8, 5, 7, 9, 10])


In [145]:
np.delete(zx, -2)

array([ 1,  2,  3,  8,  5,  7, 10])

In [146]:
zx = np.array([1, 2, 3, 8, 5, 7, 9, 10])


In [147]:
np.delete(zx, [1, 4,  -1])

array([1, 3, 8, 7, 9])

In [148]:
# ones() -----> placeholders

In [149]:
x = np.ones(10)

In [150]:
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [151]:
x = np.ones((3, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [152]:
x = np.ones((3, 3, 2))
x

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [153]:
# zeros()

In [154]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [155]:
np.zeros((4, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [157]:
# eye()

np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [158]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

    Join a sequence of arrays along an existing axis.

    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.

        .. versionadded:: 1.20.0

    casting : {'no', 'equiv', 'safe', 'same_kind', 

## numpy preactice question

Create an empty NumPy array and populate it with the multiplication table of 3, from 3x1 to 3x10.

Define a NumPy array with the elements "apple", "banana", "cherry", and then split each element into individual characters. Display the resulting array.

Generate a 5x5 NumPy array containing random integers between 1 and 100, and then find the maximum value along each row.

Create a NumPy array with the elements ["red", "green", "blue"] and then concatenate each element with the word "color". Display the resulting array.

Generate a 4x4 identity matrix using NumPy and then extract the diagonal elements.

Define a NumPy array containing the numbers 1 through 10 and reshape it into a 2x5 array. Compute the sum of each column.

Create a NumPy array with the elements ["apple", "banana", "cherry"] and then convert each element to uppercase. Display the resulting array.

Generate a 3x3 NumPy array with random floating-point numbers between 0 and 1. Round each element to two decimal places.

Define a NumPy array containing the numbers 1 through 12 and reshape it into a 3x4 array. Transpose the array and then flatten it.

Create a NumPy array with the elements ["red", "green", "blue"] and then repeat each element three times. Display the resulting array.
