In [1]:
# Numpy:

In [2]:
# Random ---> Numpy

# Random ---> python

In [3]:
# python  --> import random

# numpy

from numpy import random

In [ ]:
randint() ---->
    # randint help to get a single element randomly within the range of given perameters

In [7]:
random.randint(10, 20)

18

In [10]:
random.randint(100000, 2012121212)

387025293

In [12]:
random.randint(10, 20)

17

In [17]:
xyz = random.randint(4, 9, size = 10)

In [18]:
xyz

array([4, 8, 6, 4, 6, 5, 7, 4, 6, 4])

In [19]:
xyz.ndim

1

In [20]:
xyz = random.randint(20, 50, size = (3, 4))

In [21]:
xyz

array([[39, 35, 42, 29],
       [24, 41, 23, 28],
       [41, 33, 47, 43]])

In [22]:
xyz = random.randint(20, 50, size = (3, 4, 4))

In [23]:
xyz

array([[[26, 32, 42, 30],
        [21, 43, 44, 24],
        [20, 43, 26, 24],
        [44, 44, 48, 30]],

       [[34, 36, 30, 23],
        [30, 27, 21, 31],
        [24, 35, 35, 40],
        [46, 29, 25, 37]],

       [[32, 29, 24, 26],
        [33, 49, 43, 47],
        [25, 46, 20, 24],
        [37, 46, 26, 34]]])

In [ ]:
rand() --->

# return a single element within a spacific range i.e 0-1

In [26]:
random.rand()

0.38286460436059755

In [27]:
random.rand(10)

array([0.2048427 , 0.33113226, 0.06611535, 0.38353119, 0.69601385,
       0.81637982, 0.02504453, 0.04851555, 0.11957305, 0.32244362])

In [29]:
random.rand(2, 4)

array([[0.09808543, 0.72353914, 0.85986011, 0.29551309],
       [0.8971614 , 0.87586478, 0.61382119, 0.98777524]])

In [ ]:
randint()
rand()


choice() ----> randly elments, from the given elements

In [38]:
zx = random.choice([1, 2, 3, 41, 2, 34, 112, 34, 12])

In [39]:
zx

34

In [40]:
zx = random.choice([1, 2, 3, 41, 2, 34, 112, 34, 12], size = (3))

In [41]:
zx

array([41,  2,  3])

In [42]:
zx = random.choice([1, 2, 3, 41, 2, 34, 112, 34, 12], size = (3, 4))
zx

array([[ 41,   2,  12,   2],
       [  2,  12,  34, 112],
       [ 34, 112,  41,  34]])

In [43]:
# shuffle()

In [44]:
import numpy as np

In [61]:
zx = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
random.shuffle(zx)

In [63]:
zx

array([5, 1, 2, 8, 7, 6, 4, 3])

In [57]:
help(random.choice)

Help on built-in function choice:

choice(...) method of numpy.random.mtrand.RandomState instance
    choice(a, size=None, replace=True, p=None)

    Generates a random sample from a given 1-D array

    .. versionadded:: 1.7.0

    .. note::
        New code should use the `~numpy.random.Generator.choice`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    a : 1-D array-like or int
        If an ndarray, a random sample is generated from its elements.
        If an int, the random sample is generated as if it were ``np.arange(a)``
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    replace : boolean, optional
        Whether the sample is with or without replacement. Default is True,
        meaning that a value of ``

In [ ]:
Pandas