In [1]:
print("hello")

hello


In [2]:
print("sssss")

sssss


In [3]:
# shift + enter

In [4]:
a = 10

In [5]:
b = 20

In [6]:
c = a + b

In [7]:
c

30

# this is my heading

## this is my heading

### this is my heading

In [9]:
# sdfkdakf

In [ ]:
Numpy : --->

Numarical Python.

python : 1991

numpy : 2005
aauther -> travis oliphant


C, Java, Php, JavaScript ---> data structur 

array

array ---> python :

list
tuple
set
dictonry

In [ ]:
# array : aray is the collection homogeionus daat

# list : 

arrays:
1) homogenious data

2) 70% --< python
    30% C/C#

array --< 50x  list

In [12]:
# !pip install numpy

In [14]:
# aarays

import numpy as np

# numpy -----> ndarrays

# ndarrays --> ndimentional arrays

##### ndarray: when we create an object with the help of array method in numpy, that object is called ndarray

In [16]:
arr = np.array(100)

In [17]:
type(arr)

numpy.ndarray

In [ ]:
ndarrays : 
    1-D Array
    2-D array
    3-D array



    n-d array

In [ ]:
# 0-D array

attributes:
    ndim --< it returns the deminssion of ndarray
    shape --> return number of rows or columns

In [18]:

x = np.array(20)

In [19]:
x.ndim

0

In [20]:
x.shape

()

In [21]:
# 1-D array

x = np.array([12, 23, 34, 45, 567])

In [22]:
x

array([ 12,  23,  34,  45, 567])

In [23]:
x.ndim

1

In [24]:
x.shape

(5,)

In [27]:
# x = (34, )

# type(x)

In [28]:
# 2-D array

# combination multiple 1-D ndarrays

In [34]:
zx = np.array([[12, 23, 34, 45, 5], [34, 23, 4, 23, 54]])

In [35]:
zx

array([[12, 23, 34, 45,  5],
       [34, 23,  4, 23, 54]])

In [36]:
zx.ndim

2

In [37]:
zx.shape

(2, 5)

In [46]:
pq = np.array([[12, 23, 34], [45, 34, 45], [45, 34, 8]])

In [48]:
pq

array([[12, 23, 34],
       [45, 34, 45],
       [45, 34,  8]])

In [44]:
pq.ndim

2

In [49]:
pq.shape

(3, 3)

In [50]:
# 3-D ndarray

# combinatio  mumtllfn  2

In [55]:
zx = np.array([[[23, 34, 45], [56, 34, 23]], [[56, 34, 2], [67, 12, 34]]])

In [56]:
zx

array([[[23, 34, 45],
        [56, 34, 23]],

       [[56, 34,  2],
        [67, 12, 34]]])

In [57]:
zx.ndim

3

In [58]:
zx.shape

(2, 2, 3)

In [59]:
x = np.array([[[[[[[[5]]]]]]]])

In [60]:
x.ndim

8